package main

import (
	"fmt"
	"os"
	"os/signal"
	"runtime"
	"strings"
	"syscall"

	tunnel "github.com/dariopb/goreverselb/pkg"
	"github.com/dariopb/goreverselb/pkg/certHelper"
	"github.com/dariopb/goreverselb/pkg/helpers"
	pubsub "github.com/dariopb/goreverselb/pkg/pubsub"
	restapi "github.com/dariopb/goreverselb/pkg/restapi"
	version "github.com/dariopb/goreverselb/version"

	log "github.com/sirupsen/logrus"
	"github.com/urfave/cli/v2"
)

func printVersion() {
	log.Info(fmt.Sprintf("goreverseLB version: %v", version.Version))
	log.Info(fmt.Sprintf("Go Version: %s", runtime.Version()))
	log.Info(fmt.Sprintf("Go OS/Arch: %s/%s", runtime.GOOS, runtime.GOARCH))
}

var banner = `
                                  _     ____  
 _ __ _____   _____ _ __ ___  ___| |   | __ ) 
| '__/ _ \ \ / / _ \ '__/ __|/ _ \ |   |  _ \ 
| | |  __/\ V /  __/ |  \__ \  __/ |___| |_) )
|_|  \___| \_/ \___|_|  |___/\___|_____|____/ 
`

func main() {
	banner = strings.ReplaceAll(banner, "#", "`")
	fmt.Println(banner)

	app := &cli.App{
		EnableBashCompletion: true,
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:        "loglevel",
				Aliases:     []string{"l"},
				Value:       "info",
				Usage:       "debug level, one of: info, debug",
				EnvVars:     []string{"REVLB_LOGLEVEL"},
				Destination: &cfg.LogLevel,
			},
			&cli.StringFlag{
				Name:        "token",
				Aliases:     []string{"t"},
				Usage:       "shared secret for authorization",
				EnvVars:     []string{"REVLB_TOKEN"},
				Destination: &cfg.Token,
				Required:    true,
			},
		},
		Commands: []*cli.Command{
			{
				Name: "server",
				//Aliases: []string{"server"},
				Usage:  "runs as a server",
				Action: server,

				Flags: []cli.Flag{
					&cli.IntFlag{
						Name:        "port",
						Aliases:     []string{"p"},
						Value:       0,
						Usage:       "port for the API endpoint",
						EnvVars:     []string{"REVLB_PORT"},
						Destination: &cfg.Port,
						Required:    true,
					},

					&cli.StringFlag{
						Name:        "autocertsubjectname",
						Aliases:     []string{"s"},
						Value:       "",
						Usage:       "subject name for the autogenerated certificate",
						EnvVars:     []string{"REVLB_AUTO_CERT_SUBJECT_NAME"},
						Destination: &cfg.AutoCertSubjectName,
						Required:    true,
					},
					&cli.IntFlag{
						Name:        "httpport",
						Value:       0,
						Usage:       "port for the HTTP rest endpoint (server will be disabled if not provided)",
						EnvVars:     []string{"REVLB_HTTP_PORT"},
						Destination: &cfg.HTTPPort,
						Required:    false,
					},
					&cli.IntFlag{
						Name:        "natsport",
						Value:       0,
						Usage:       "port for the secure NATS endpoint (server will be disabled if not provided)",
						EnvVars:     []string{"REVLB_NATS_PORT"},
						Destination: &cfg.NATSPort,
						Required:    false,
					},
					&cli.IntFlag{
						Name:        "dynport",
						Value:       8000,
						Usage:       "dynamic frontend port base",
						EnvVars:     []string{"REVLB_DYN_FRONTEND_PORT"},
						Destination: &cfg.DynPort,
						Required:    false,
					},
					&cli.IntFlag{
						Name:        "dynportcount",
						Value:       100,
						Usage:       "number of dynamic frontend ports",
						EnvVars:     []string{"REVLB_DYN_FRONTEND_PORT_COUNT"},
						Destination: &cfg.DynPortCount,
						Required:    false,
					},
				},
			},
			{
				Name: "tunnel",
				//Aliases: []string{"tunnel"},
				Usage:  "creates an ingress tunnel",
				Action: client,

				Flags: []cli.Flag{
					&cli.StringFlag{
						Name:        "apiendpoint",
						Aliases:     []string{"e"},
						Value:       "",
						Usage:       "API endpoint in the form: hostname:port",
						EnvVars:     []string{"REVLB_API_ENDPOINT"},
						Destination: &cfg.APIEndpoint,
						Required:    true,
					},
					&cli.IntFlag{
						Name:        "frontendport",
						Aliases:     []string{"p"},
						Value:       0,
						DefaultText: "auto",
						Usage:       "frontend port where the service is going to be exposed (endpoint will be apiendpoint:serviceport)",
						EnvVars:     []string{"REVLB_FRONTEND_PORT"},
						Destination: &cfg.FrontendPort,
						Required:    false,
					},
					&cli.BoolFlag{
						Name:        "wraptls",
						Aliases:     []string{"w"},
						Value:       false,
						Usage:       "always wrap the frontend connection as TLS (exposes HTTP backend as HTTPS endpoint)",
						EnvVars:     []string{"REVLB_WRAP_TLS"},
						Destination: &cfg.WrapTLS,
						Required:    false,
					},
					&cli.BoolFlag{
						Name:        "wrapSSH",
						Value:       false,
						Usage:       "always wrap the frontend connection as SSH tunnel",
						EnvVars:     []string{"REVLB_WRAP_SSH"},
						Destination: &cfg.WrapSSH,
						Required:    false,
					},

					&cli.StringFlag{
						Name:        "serviceendpoint",
						Aliases:     []string{"b"},
						Value:       "",
						Usage:       "backend service address (the local target for the lb: hostname:port)",
						EnvVars:     []string{"REVLB_SERVICE_ENDPOINT"},
						Destination: &cfg.ServiceEndpoint,
						Required:    true,
					},
					&cli.StringFlag{
						Name:        "servicename",
						Aliases:     []string{"s"},
						Usage:       "service name string",
						EnvVars:     []string{"REVLB_SERVICE_NAME"},
						Destination: &cfg.ServiceName,
						Required:    true,
					},
					&cli.StringFlag{
						Name:        "instancename",
						Value:       "",
						DefaultText: "empty",
						Usage:       "instance name string (for SNI/Host functionality)",
						EnvVars:     []string{"REVLB_INSTANCE_NAME"},
						Destination: &cfg.InstanceName,
						Required:    false,
					},
					&cli.BoolFlag{
						Name:        "insecuretls",
						Aliases:     []string{"i"},
						Value:       false,
						Usage:       "allow skip checking server CA/hostname",
						EnvVars:     []string{"REVLB_INSECURE_TLS"},
						Destination: &cfg.InsecureTLS,
						Required:    false,
					},
				},
			},
			{
				Name:   "tunnelgroup",
				Usage:  "creates multiple ingress tunnels",
				Action: servicegroup,

				Flags: []cli.Flag{
					&cli.StringFlag{
						Name:        "apiendpoint",
						Aliases:     []string{"e"},
						Value:       "",
						Usage:       "API endpoint in the form: hostname:port",
						EnvVars:     []string{"REVLB_API_ENDPOINT"},
						Destination: &cfg.APIEndpoint,
						Required:    true,
					},
					&cli.StringFlag{
						Name:        "servicegroup",
						Aliases:     []string{"g"},
						Value:       "",
						DefaultText: "",
						Usage:       "service group json: like: '{\"ssh1\":{\"name\":\"ssh1\",\"ports\":[{\"port\":8000,\"protocol\":\"tcp\",\"targetPort\":22}],\"backendIPs\":[\"127.0.0.1\"],\"deleted\":false}}'",
						EnvVars:     []string{"REVLB_SERVICE_GROUP_JSON"},
						Destination: &cfg.ServiceGroupJSON,
						Required:    true,
					},
				},
			},
			{
				Name: "stdinproxy",
				//Aliases: []string{"tunnel"},
				Usage:  "creates an stdin/stdout proxy to the endpoint",
				Action: stdinProxy,

				Flags: []cli.Flag{
					&cli.StringFlag{
						Name:        "serviceendpoint",
						Aliases:     []string{"e"},
						Value:       "",
						Usage:       "backend service address (hostname:port)",
						EnvVars:     []string{"REVLB_SERVICE_ENDPOINT"},
						Destination: &cfg.ServiceEndpoint,
						Required:    true,
					},
					&cli.StringFlag{
						Name:        "instancename",
						Value:       "",
						DefaultText: "empty",
						Usage:       "instance name string (for SNI/Host functionality)",
						EnvVars:     []string{"REVLB_INSTANCE_NAME"},
						Destination: &cfg.InstanceName,
						Required:    false,
					},
					&cli.BoolFlag{
						Name:        "wraptls",
						Aliases:     []string{"w"},
						Value:       false,
						Usage:       "wrap the client connection on TLS (most likely the backend should be wrapped as well)",
						EnvVars:     []string{"REVLB_WRAP_TLS"},
						Destination: &cfg.WrapTLS,
						Required:    false,
					},
					&cli.BoolFlag{
						Name:        "insecuretls",
						Aliases:     []string{"i"},
						Value:       false,
						Usage:       "allow skip checking server CA/hostname",
						EnvVars:     []string{"REVLB_INSECURE_TLS"},
						Destination: &cfg.InsecureTLS,
						Required:    false,
					},
				},
			},
		},

		Name:  "goreverselb",
		Usage: "create tunnel proxies and load balance traffic between them",
		//Action: goreverselbserver,
	}

	err := app.Run(os.Args)
	if err != nil {
		log.Fatal(err)
	}
}

func server(ctx *cli.Context) error {
	printVersion()

	loglevel := log.InfoLevel
	if l, err := log.ParseLevel(cfg.LogLevel); err == nil {
		loglevel = l
	}

	//log.AddHook(ProcessCounter)
	//log.SetFormatter(&log.TextFormatter{ForceColors: true})
	log.SetLevel(loglevel)
	log.SetOutput(os.Stdout)

	// Initialize/retrieve the persistent runtime data
	configData := &tunnel.ConfigData{}
	store, err := helpers.NewAppData("user_store.yaml")
	store.LoadConfig(configData, false, func() (interface{}, error) {
		configData.Users = map[string]*tunnel.UserData{
			tunnel.DefaultUserID: {UserID: tunnel.DefaultUserID,
				AllowedSources: "*"},
		}

		return configData, nil
	})
	if err != nil {
		log.Fatal("failed to load user configuration: ", err)
	}

	configData.Users[tunnel.DefaultUserID].Token = cfg.Token
	store.Save()

	cert, err := certHelper.CreateDynamicTlsCertWithKey(cfg.AutoCertSubjectName)
	if err != nil {
		log.Fatalf("failed to create tls certificate: %v", err)
	}

	ts, err := tunnel.NewMuxTunnelService(configData, *cert, cfg.Port, cfg.Token, cfg.DynPort, cfg.DynPortCount)
	if err != nil {
		log.Fatalf("failed to start new tunnel service: %v", err)
	}

	if cfg.NATSPort != 0 {
		pubsub.NewNatsServer(*cert, cfg.NATSPort, cfg.Token)
	} else {
		log.Debug("natsport not provided, not starting NATS server")
	}

	if cfg.HTTPPort != 0 {
		restapi.NewRestApi(*cert, cfg.HTTPPort, cfg.Token, ts)
	} else {
		log.Debug("httpport not provided, not starting HTTP server")
	}

	c := make(chan os.Signal, 2)
	signal.Notify(c, os.Interrupt, syscall.SIGTERM)

	<-c

	ts.Close()

	return err
}
